services:
  cosyvoice2-cuda:
    image: ghcr.io/seancheung/cosyvoice-openai-tts-api:cuda-latest
    ports:
      - "8002:8000"
    volumes:
      - ./models/CosyVoice2-0.5B:/models:ro
      - ./voices:/voices:ro
      - ./cache:/root/.cache
    environment:
      COSYVOICE_VERSION: "2"
      COSYVOICE_FP16: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  cosyvoice3-cuda:
    image: ghcr.io/seancheung/cosyvoice-openai-tts-api:cuda-latest
    ports:
      - "8003:8000"
    volumes:
      - ./models/Fun-CosyVoice3-0.5B:/models:ro
      - ./voices:/voices:ro
      - ./cache:/root/.cache
    environment:
      COSYVOICE_VERSION: "3"
      COSYVOICE_FP16: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  cosyvoice2-cpu:
    image: ghcr.io/seancheung/cosyvoice-openai-tts-api:latest
    ports:
      - "8012:8000"
    volumes:
      - ./models/CosyVoice2-0.5B:/models:ro
      - ./voices:/voices:ro
      - ./cache:/root/.cache
    environment:
      COSYVOICE_VERSION: "2"

  cosyvoice3-cpu:
    image: ghcr.io/seancheung/cosyvoice-openai-tts-api:latest
    ports:
      - "8013:8000"
    volumes:
      - ./models/Fun-CosyVoice3-0.5B:/models:ro
      - ./voices:/voices:ro
      - ./cache:/root/.cache
    environment:
      COSYVOICE_VERSION: "3"
